### ISSUE TITLE
File copy progress

### ISSUE THREAD

**Issue by shanmukhateja** [timkendrick/recursive-copy#12]
Hello,

I was wondering if there's a way to get the overall copy progress.

In my use case, I currently have a directory of about 1.3GB in size and I would like to show a progress bar for the user while the copy is under way.

**Comment by shanmukhateja** [comment]
I have the following:

```
// total no of files
    let totalFiles = this._totalFiles(finalSrc)
    let currentIndex = 1;
    // show progress bar
    this.showProgressBar = true
    // init rcopy
    var options = {
      overwrite: true,
      expand: true,
      dot: true,
      junk: true
    };
    rcopy(src, dest, options)
      // will be called after a file is copied
      .on(rcopy.events.COPY_FILE_COMPLETE, function (copyOperation) {
        // increment counter and update user
        currentIndex += 1
        // every 4rd file, update progress bar
        if (currentIndex % 4 == 0) {
          self.updateProgress(totalFiles, currentIndex)
        }
      })
      .then(results => {
        // hide progress bar
        self.showProgressBar = false
        console.info('Copied ' + results.length + ' files');
      })
      .catch(function (error) {
        console.error('Copy failed: ' + error);
      });
```
Although the progress bar moving forward, it seems some files are being copied even after the progress bar reaches 100%.

I'm using Angular 6 if that helps!

**Comment by timkendrick** [comment]
Hey – you're definitely going about it correctly; the only thing that jumps out at me is that you're initializing your `currentIndex` at `1`, and incrementing it every time a file completes.

This means that if say you have 4 files, when the **second-last** one completes you call `self.updateProgress(totalFiles, 4)`. I'm guessing `totalFiles` would be `4` in this case, so that would be the same as `self.updateProgress(4, 4)`, when the second-last file completes. Depending on how the `updateProgress` method is implemented , maybe this would set it to 100%, even though there is still one more file to go? If so, this could be fixed by initializing `currentIndex` to `0`, not `1`. Maybe give that a try?

If that doesn't fix it, it might be worth logging the `totalFiles` and `currentIndex` arguments in the first line of your `self.updateProgress()` method and check that they are what you expect. I don't know how you're calculating `totalFiles`, but it should end up as the same value as the `results.length` that is logged once the copy completes successfully. If `totalFiles` is less than this value (maybe due to hidden files etc) then your percentage indicator will reach 100% before the copy is finished.

Other than that, if you can create a PR with a failing test case then I'll gladly take a look into it.

**Comment by timkendrick** [comment]
Closing due to lack of response – feel free to reopen if you feel this is a mistake
