### ISSUE TITLE
Modifies Promise built-in

### ISSUE THREAD

**Issue by novemberborn** [timkendrick/recursive-copy#5]
Hiya! I'm evaluating modules to copy directory structures and came across this one. There's a deprecation warning for the [`promise.prototype.finally`](https://www.npmjs.com/package/promise.prototype.finally) dependency. Suspicious of the name I looked at what it does, and it indeed modifies the `Promise` built-in. Given that `finally()` is only used once that seems unnecessary.

(Generally I think modifying built-ins, if done at all, should be done by applications, not by packages like this.)

**Comment by timkendrick** [comment]
Good point – when I wrote this a couple years back I don't think promises were part of Node core, so I used the [promise](https://www.npmjs.com/package/promise) library, which comes with a `.finally()` method. When upgrading to native promises it looks like I just papered over the cracks rather than removing the `.finally()` calls.

That should be fixed now, let me know if you have any problems.

**Comment by novemberborn** [comment]
Nice one, thanks!
